err_chk

diff --git a/jobs/JWAMIPE_ANALYSIS b/jobs/JWAMIPE_ANALYSIS
--- a/jobs/JWAMIPE_ANALYSIS
+++ b/jobs/JWAMIPE_ANALYSIS
@@ -49,8 +49,7 @@ export EXPDIR=${EXPDIR:-$HOMEwamipe/parm/config}
 config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
 for config in $configs; do
     . $config_path/config.$config
-    status=$?
-    [[ $status -ne 0 ]] && exit $status
+    export err=$?; err_chk "Error sourcing config files in $config_path"
 done
 
 while read line; do export $line ; done < <($HOMEwamipe/ush/create_config.py \
@@ -60,8 +59,7 @@ while read line; do export $line ; done < <($HOMEwamipe/ush/create_config.py \
 # Source machine runtime environment
 ##########################################
 . $HOMEwamipe/env/${machine}.env anal
-status=$?
-[[ $status -ne 0 ]] && exit $status
+export err=$? ; err_chk "GSI analysis or sfc analysis failure"
 
 
 ##############################################
@@ -107,8 +105,7 @@ fi
 
 
 export LEVS=$($SIGHDR $ATMGES levs)
-status=$?
-[[ $status -ne 0 ]] && exit $status
+export err=$? ; err_chk "Failure to get levs from $ATMGES using $SIGHDR"
 
 
 if [ $DOHYBVAR = "YES" ]; then
@@ -149,8 +146,7 @@ $LOGSCRIPT
 
 
 ${ANALYSISSH:-$SCRgsi/exglobal_analysis_fv3gfs.sh.ecf}
-status=$?
-[[ $status -ne 0 ]] && exit $status
+export err=$? ; err_chk "Failure during GSI analysis or sfc analysis"
 
 
 ##############################################
